---
title: "02_LH-SIP_Quantification"
author: "Tristan Caro"
date: "3/23/2022"
output: html_document
---

# Setup

```{r setup, include = FALSE}
# global knitting options for code rendering
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>")

# global knitting options for automatic saving of all plots as .png and .pdf
knitr::opts_chunk$set(
  dev = c("png", "pdf"),
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.keep = "all",
  fig.path = file.path("fig_output", paste0(gsub("\\.[Rr]md", "", knitr::current_input()), "_"))
)
```

## Load packages

```{r, message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)    # CRAN v1.3.1
library(forcats)      # CRAN v0.5.1 
library(isoreader)    # [::NA/NA] v1.3.0 # CRAN v1.3.0
library(isoprocessor) # [github::isoverse/isoprocessor] v0.6.7
library(isotopia)     # [github::isoverse/isotopia] v0.5.8 
library(readxl)       # CRAN v1.3.1 
library(ggsci)        # CRAN v2.9 
library(ggborderline) # [github::wurli/ggborderline] v0.1.0
library(ggrepel)      # CRAN v0.9.1 
library(latex2exp)    # CRAN v0.5.0
library(ggdist)       # CRAN v3.0.0 
library(ggsignif)     # CRAN v0.6.2
library(ggridges)     # CRAN v0.5.3
library(cowplot)      # CRAN v1.1.1
```

## Load sourced functions
These functions are found in the `libs/` directory.
```{r}
# Sourced Functions
source(file.path("libs", "visualization.R"))              # Visualization scripts
source(file.path("libs", "chromeleon.R"))                 # Chromeleon Reader
source(file.path("libs", "error_prop.R"))                 # Error Propagation
source(file.path("libs", "calculate_turnover.R"))         # Calculate turnover rate
source(file.path("libs", "turnover_to_gen.R"))            # Turnover rate to generation time
`%nin%` = Negate(`%in%`)                                  # "Not In" function
var_to_str = function(v) {return(deparse(substitute(v)))} # Convert variable name to string
```

## Read RDS from cache

```{r}
LH_SIP_data <- readRDS(file = "cache/LH_SIP_data")
LH_SIP_data_3d_onwards <- readRDS(file = "cache/LH_SIP_data_3d_onwards")
LH_SIP_memcorr <- readRDS(file = "cache/LH_SIP_memcorr")
```

# Calculate Turnover

```{r}
turnover <- LH_SIP_data %>% 
  # Combine 0d --> and 3d --> datasets
  bind_rows(LH_SIP_data_3d_onwards) %>% 
  # Evaluate each row individually
  ungroup() %>%
  mutate(
    
    # Explicitly define incubation parameters:
    # label is adjusted for the actual isotopic composition of the label within a specific terrain
    f_label = F_label_mn,
    # start time
    t0 = case_when(
      time_course == "0d -->" ~ 0,
      time_course == "3d -->" ~ 3),
    d_t = inc_time_d - t0, # change in time
    f_start = case_when(
      time_course == "0d -->" ~at2H_mn_zero,
      time_course == "3d -->" ~ at2H_mn_three),
    # use PAME-corrected 2F value
    f_t = `2F_alk`,
    # delta 2F: change in 2F enrichment over time t
    dF = case_when(
      f_t - f_start >= 0 ~ f_t - f_start,
      f_t - f_start < 0 ~ 0),
    # Calculate Turnover Rate in days from day 0 to 7 and 0 to 3
    u_d = calculate_turnover(
      a = a, # Assimilation efficiency defined in data reduction step
      FT = f_t, # 2F at time t (at%)
      F0 = f_start, # 2F at t0 (at%)
      FL = f_label, # 2F of label (at%)
      t = d_t # change in time
      ),
    # calculate generation time, converting negatives to zero
    gen_d = turnover_to_gen(u_d),
    
    # Calculate uncertainty in turnover rate
    su_d = calculate_sigma_mu(
      # Mean values:
      a = a,
      F_L = f_label,
      F_T = f_t,
      F_0 = f_start,
      t = d_t,
      # Uncertainties:
      sF_0 = F_0_at2H_se,
      sF_L = F_label_se,
      sF_T = 0,
      sa = sa
    )
    
  )
```

# Create weighted turnover


```{r}
# Create a summarized dataframe grouped by experimental replicates
turnover_summarized <- turnover %>% 
  group_by(
    time_course,
    terrain, 
    inc_time_d,
    compound
  ) %>% 
  dplyr::summarize_if(
    is.numeric, 
    mean, 
    na.rm = TRUE
  )

# Summarize by combining experimental replicates

LH_SIP_data_summarized <- LH_SIP_data %>% 
  group_by(
    terrain, 
    inc_time_d, 
    compound
  ) %>% 
  # FILTER OUT NON BACTERIAL COMPOUNDS
  filter(compound %nin% c("20:0", "22:0", "24:0")) %>% 
  summarize_if(
    is.numeric, 
    mean, 
    na.rm = TRUE
  )


weighted_time_course <- LH_SIP_data_summarized %>%
  group_by(
    terrain, 
    inc_time_d
  ) %>% 
  dplyr::summarize(
    # Weight at2H
    at2H_weighted = 
      sum(at2H * rel_area_FID, na.rm = TRUE) / 
      sum(rel_area_FID, na.rm = TRUE),
    # Weight `2F_alk`
    `2F_alk_weighted` = 
      sum(`2F_alk` * rel_area_FID, na.rm = TRUE) / 
      sum(rel_area_FID, na.rm = TRUE),
    # Keep these:
    f_label = mean(F_label_mn, na.rm = TRUE),
    a = 0.6,
    t0 = 0,
    d_t = inc_time_d - t0, # change in time
    f_start = mean(at2H_mn_zero, na.rm = TRUE),
    f_t = `2F_alk_weighted`,
    dF_weighted = case_when(
      f_t - f_start >= 0 ~ f_t - f_start,
      f_t - f_start < 0 ~ 0),
  ) %>%
  dplyr::summarize_if(
    is.numeric,
    mean,
    na.rm = TRUE
  ) %>%
  mutate(
    u_d_weighted = calculate_turnover(
      a = a,
      FT = f_t,
      F0 = f_start,
      FL = f_label,
      t = d_t
    ),
    gen_d_weighted = turnover_to_gen(u_d_weighted)
  )
```



# Export
```{r}
turnover %>% saveRDS(file = "cache/turnover_rates")

turnover_summarized %>% saveRDS(file = "cache/turnover_summarized")

weighted_time_course %>% saveRDS(file = "cache/turnover_weighted")
```

