---
title: "03 Data Vizualization"
author: "Tristan Caro"
date: "`r Sys.Date()`"
output:
    html_document:
    code_folding: show
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r, echo = FALSE, warning = FALSE, message=FALSE}
library(tidyverse)    # CRAN v1.3.1    
library(forcats)      # CRAN v0.5.1      
library(isoreader)    # CRAN v1.3.0    
library(isoprocessor) # [github::isoverse/isoprocessor] v0.6.7 
library(isotopia)     # [github::isoverse/isotopia] v0.5.8     
library(readxl)       # CRAN v1.3.1       
library(ggsci)        # CRAN v2.9        
library(ggborderline) # [github::wurli/ggborderline] v0.1.0 
library(ggrepel)      # CRAN v0.9.1      
library(latex2exp)    # CRAN v0.5.0    
library(ggdist)       # CRAN v3.0.0       
library(ggsignif)     # CRAN v0.6.2     
library(ggridges)     # CRAN v0.5.3     
library(ggalluvial)   # CRAN v0.12.3   
library(cowplot)      # CRAN v1.1.1      
library(scales)       # CRAN v1.1.1
```

# Load sourced functions

```{r}
# Sourced Functions
source(file.path("libs", "visualization.R"))
source(file.path("libs", "chromeleon.R"))
source(file.path("libs", "error_prop.R"))
source(file.path("libs", "calculate_turnover.R"))
source(file.path("libs", "turnover_to_gen.R"))
`%nin%` = Negate(`%in%`) # "Not In" function
var_to_str = function(v) {return(deparse(substitute(v)))} # Convert variable name to string
```

# Setup


## Read RDS from cache

```{r workspace images}
# Turnover data
turnover <- readRDS("cache/turnover_rates")

# Summarized turnover

turnover_summarized <- readRDS("cache/turnover_summarized")

# Weighted turnover data
turnover_weighted <- readRDS("cache/turnover_weighted")

# LH-SIP data
LH_SIP_data <- readRDS(file = "cache/LH_SIP_data")

# LH-SIP data but with 3d as the starting timepoint
LH_SIP_data_3d_onwards <- readRDS(file = "cache/LH_SIP_data_3d_onwards")

# BacDive Data
bacdive_FA <- readRDS(file = "cache/bacdive_FA")
bacdive_FA_wide <- readRDS(file = "cache/bacdive_FA_wide")

# IRMS chromatogram data
sample_files <- readRDS(file = "cache/sample_files")
```

### Lit search data

```{r lit search data}
lit_turnover <- readxl::read_excel(file.path("data", "literature_turnover_rates.xlsx"))
turnover_means <- turnover_weighted %>% 
  filter(inc_time_d == 7) %>%
  select(terrain, u_d_weighted) %>% 
  rename(u_d_mn = u_d_weighted) %>% 
  mutate(comment = terrain) %>% 
  mutate(n = case_when(
    terrain == "Niwot Ridge Tundra" ~ 3,
    terrain == "Gordon Gulch Conifer Forest" ~ 1,
    terrain == "Marshall Mesa Grassland" ~ 2
  )) %>% 
  mutate(method = "LH-SIP",
         method_type = "LH-SIP")

lit_turnover_w_ours <- lit_turnover %>% bind_rows(turnover_means) %>% 
  # Convert to generation time:
  mutate(gen_d = turnover_to_gen(u_d_mn))
```


## Set color swatches

```{r color swatches}
tundra_color <- "#4ebad5"

grassland_color <- "#01a088"

conifer_color <- "#e64a35"

terrain_color_swatch <- c(conifer_color, grassland_color, tundra_color)
terrain_fill_swatch <- c(conifer_color, grassland_color, tundra_color)
```


# Plots



```{r mean_generation_time}
p_gen_time_mean <- turnover_weighted %>% 
  filter(inc_time_d == 7) %>% 
  mutate(terrain = case_when(
    terrain == "Gordon Gulch Conifer Forest" ~ "Conifer Forest",
    terrain == "Marshall Mesa Grassland" ~ "Grassland",
    terrain == "Niwot Ridge Tundra" ~ "Tunrda" )) %>% 
  group_by(terrain, inc_time_d) %>% 
  summarize(terrain = terrain,
            gen_d_weighted = gen_d_weighted) %>% 
  unique() %>% 
  ggplot(aes(x = terrain,
             y = gen_d_weighted,
             fill = terrain)) +
  geom_col(width = 0.5) +
  scale_fill_manual(values = terrain_fill_swatch) +
  labs(x = "Soil Type",
       y = "Community Generation Time (d)",
       caption = "Generation time weighted by compound relative abundance") +
  theme_classic() +
  theme(legend.position = "none")
p_gen_time_mean
```

```{r cowplot mooooo}
p_community_turnover_cow <- cowplot::plot_grid(
  p_turnover_distributions,
  p_gen_time_mean,
  labels = "AUTO",
  rel_widths = c(1,1),
  align = "h",
  nrow = 1
) 

# 
# save_plot(filename = "fig_output/p_community_turnover_cow.png",
#           plot = p_community_turnover_cow,
#           base_height = 5,
#           base_width = 10
#           )

```



## dF and turnover plot

```{r}
p_dF <- turnover_summarized %>% 
  filter(time_course == "0d -->") %>% 
  ungroup() %>% 
  select(terrain, inc_time_d, compound, dF) %>%
  left_join(
    turnover_weighted %>% 
      select(terrain, inc_time_d, dF_weighted), 
    by = c("terrain", "inc_time_d")) %>% 
  group_by(
    terrain,
    inc_time_d
  ) %>% 
  pivot_longer(
    cols = c(dF, dF_weighted),
    values_to = "dF", 
    names_to = "type"
  ) %>% 



  ggplot(
    aes(
      x = inc_time_d,
      y = dF
    )
  ) +
  # Weighted data here:
  geom_line(aes(
    x = inc_time_d,
    y = dF_weighted,
    color = terrain),
    size = 1.5,
    alpha = 0.5
    ) +
  geom_point(
    aes(
      x = inc_time_d,
      y = dF_weighted,
      color = terrain,
      fill = terrain),
    size = 2,
    alpha = 0.5
    ) +
  # Unweighted data here:
  geom_borderline(
    data = turnover_summarized,
    aes(group = compound),
    color = "gray"
) +
  geom_point(
    data = turnover_summarized,
    size = 2,
    alpha = 0.5
    ) +
  scale_x_continuous(breaks = c(0, 1,2,3,4,5,6,7)) +
  coord_cartesian(
    xlim = c(0, 8),
    clip = "off"
    ) +
  facet_wrap(vars(terrain),
             nrow = 1) +
  labs(x = "Incubation Time (Days)",
       y = TeX("$ \\Delta ^2H$ (at%)"),
       ) +
  scale_color_manual(values = terrain_color_swatch) +
  scale_fill_manual(values = terrain_fill_swatch) +
  theme_classic() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(size = 10))

p_dF
```


```{r 2H_plots}

peaks_mapped_summarized_wppm <- turnover_summarized %>% 
    mutate(at2H_ppm = at2H * 10000,
         at2H_mn_zero_ppm = at2H_mn_zero * 10000,
         at2H_weighted_ppm = at2H_weighted * 10000)


p_conifer_2H <- peaks_mapped_summarized_wppm %>% 
  filter(terrain == "Gordon Gulch Conifer Forest") %>% 
  ggplot(aes(x = inc_time_d,
             y = at2H_ppm,
             group = compound)) +
  geom_borderline(color = "gray") +
  geom_point(size = 2,
             alpha = 0.5) +
  geom_borderline(aes(x = inc_time_d,
                y = at2H_weighted_ppm),
                color = conifer_color,
            size = 1.5) +
  geom_point(aes(x = inc_time_d,
                y = at2H_weighted_ppm), 
                color = conifer_color,
             size = 3,
             alpha = 0.5) +
  scale_x_continuous(breaks = c(0, 1,2,3,4,5,6,7)) +
  coord_cartesian(xlim = c(0, 8), ylim = c(0, 1300), clip = "off") +
  labs(x = "Incubation Time (Days)",
       y = TeX("$^2H$ (ppm)"),
       title = "Conifer Forest") +
  theme_classic() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(size = 10))
p_conifer_2H



p_grassland_2H <- peaks_mapped_summarized_wppm %>% 
  filter(terrain == "Marshall Mesa Grassland") %>% 
  mutate(compound = forcats::fct_reorder(compound, rt)) %>% 
  ggplot(aes(x = inc_time_d,
             y = at2H_ppm,
             group = compound)) +
  geom_borderline(color = "gray") +
  geom_point(size = 2,
             alpha = 0.5) +
  geom_borderline(aes(x = inc_time_d,
                      y = at2H_weighted_ppm),
                      color = grassland_color,
                  size = 1.5) +
  geom_point(aes(x = inc_time_d,
                 y = at2H_weighted_ppm), 
                 color = grassland_color,
             size = 3) +
  scale_x_continuous(breaks = c(0, 1,2,3,4,5,6,7)) +
  coord_cartesian(xlim = c(0, 8), ylim = c(0, 1300), clip = "off") +
  labs(x = "Incubation Time (Days)",
       y = TeX("$^2H$ (ppm)"),
       title = "Grassland") +
  theme_classic() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(size = 10))
p_grassland_2H



p_tundra_2H <- peaks_mapped_summarized_wppm %>% 
  filter(terrain == "Niwot Ridge Tundra") %>% 
  mutate(compound = forcats::fct_reorder(compound, rt)) %>% 
  ggplot(aes(x = inc_time_d,
             y = at2H_ppm,
             group = compound)) +
  geom_borderline(color = "gray") +
  geom_point(size = 2,
             alpha = 0.5) +
  geom_borderline(aes(x = inc_time_d,
                y = at2H_weighted_ppm),
                color = tundra_color,
            size = 1.5) +
  geom_point(aes(x = inc_time_d,
                y = at2H_weighted_ppm), 
                color = tundra_color,
                fill = tundra_color,
             size = 3) +
  scale_x_continuous(breaks = c(0, 1,2,3,4,5,6,7)) +
  coord_cartesian(xlim = c(0, 8), ylim = c(0, 1300), clip = "off") +
  labs(x = "Incubation Time (Days)",
       y = TeX("$^2H$ (ppm)"),
       title = "Tundra") +
  theme_classic() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(size = 10))
p_tundra_2H
```


```{r}

p_tundra_2H_3d <- peaks_mapped_summarized_wppm %>% 
  filter(terrain == "Niwot Ridge Tundra") %>% 
  mutate(compound = forcats::fct_reorder(compound, rt)) %>% 
  ggplot(aes(x = inc_time_d,
             y = at2H_ppm,
             group = compound)) +
  geom_borderline(color = "gray") +
  geom_point(size = 2,
             alpha = 0.5) +
  geom_borderline(aes(x = inc_time_d,
                y = at2H_weighted_ppm),
                color = tundra_color,
            size = 1.5) +
  geom_point(aes(x = inc_time_d,
                y = at2H_weighted_ppm), 
                color = tundra_color,
                fill = tundra_color,
             size = 3) +
  scale_x_continuous(breaks = c(0, 1,2,3,4,5,6,7)) +
  coord_cartesian(xlim = c(0, 8), ylim = c(0, 1300), clip = "off") +
  labs(x = "Incubation Time (Days)",
       y = TeX("$^2H$ (ppm)"),
       title = "Tundra") +
  theme_classic() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(size = 10))
p_tundra_2H
```



```{r turnover_plots}
add_weighted_mean <- function(df) {
  df %>% 
    ungroup() %>% 
    mutate(type = "sample") %>% 
    add_row(compound = "Weighted Mean",
            u_d_weighted = df$u_d_weighted[1],
            terrain = df$terrain[1],
            u_d = df$u_d_weighted[1],
            type = "Weighted Mean")
}

# Add weighted generation time

summarized_weighted_gen_d <- gen_calc_data_summarized_weighted %>% 
  filter(inc_time_d == 7) %>% 
  select(terrain, gen_d_weighted) %>% 
  unique()


p_conifer_u_d <- gen_calc_data_summarized_weighted %>%
  filter(terrain == "Gordon Gulch Conifer Forest",
         inc_time_d == 7) %>% 
  select(terrain, inc_time_d, compound, u_d, u_d_weighted) %>%
  add_weighted_mean() %>% 
  mutate(compound = forcats::fct_reorder(compound, u_d)) %>%
  # PLOT IT
  ggplot() +
  geom_col(aes(x = compound,
               y = u_d, 
               fill = type)) +
  scale_fill_manual(values = c("#000000", conifer_color)) +
  # Secondary axis option:
  # scale_y_continuous(sec.axis = sec_axis(trans = ~ log(2)/.,
  #                                        breaks = c(7, 14, 30, 90, 365),
  #                                        name = "Generation time (d)")) +
  coord_flip(ylim = c(0, 0.09), clip = "off") +
  labs(y = TeX("Turnover ($d^{-1}$)"),
       title = "Conifer Forest") +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5))
p_conifer_u_d


p_grassland_u_d <- gen_calc_data_summarized_weighted %>% 
  filter(terrain == "Marshall Mesa Grassland",
         inc_time_d == 7) %>% 
  select(terrain, inc_time_d, compound, u_d, u_d_weighted) %>% 
  add_weighted_mean() %>% 
  mutate(compound = forcats::fct_reorder(compound, u_d)) %>%
  # PLOT IT
  ggplot() +
  geom_col(aes(x = compound, y = u_d, fill = type)) +
  scale_fill_manual(values = c("#000000", grassland_color)) +
  coord_flip(ylim = c(0, 0.09), clip = "off") +
  labs(y = TeX("Turnover ($d^{-1}$)"),
       title = "Grassland") +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5))

p_tundra_u_d <- gen_calc_data_summarized_weighted %>% 
  filter(terrain == "Niwot Ridge Tundra",
         inc_time_d == 7) %>% 
  select(terrain, inc_time_d, compound, u_d, u_d_weighted) %>% 
  add_weighted_mean() %>% 
  mutate(compound = forcats::fct_reorder(compound, u_d)) %>%
  # PLOT IT
  ggplot() +
  geom_col(aes(x = compound, y = u_d, fill = type)) +
  scale_fill_manual(values = c("#000000", tundra_color)) +
  # Add weighted generation time label
  coord_flip(ylim = c(0, 0.09), clip = "off") +
  labs(y = TeX("Turnover ($d^{-1}$)"),
       title = "Tundra") +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5))
p_tundra_u_d
```



```{r moo}
# HORIZONTAL
p_turnover_enrichment_cow_h <- cowplot::plot_grid(
  p_conifer_2H,
  p_grassland_2H,
  p_tundra_2H,
  p_conifer_u_d,
  p_grassland_u_d,
  p_tundra_u_d,
  labels = "AUTO",
  rel_widths = c(1,1),
  align = "h",
  nrow = 2
) 

p_turnover_enrichment_cow_h
# 
# cowplot::save_plot(filename = "fig_output/p_turnover_enrichment_cow_horiz.pdf",
#           plot = p_turnover_enrichment_cow,
#           base_height = 8,
#           base_width = 12
#           )


# VERTICAL
p_turnover_enrichment_cow_v <- cowplot::plot_grid(
  p_conifer_2H,
  p_conifer_u_d,
  p_grassland_2H,
  p_grassland_u_d,
  p_tundra_2H,
  p_tundra_u_d,
  labels = "AUTO",
  rel_widths = c(1,1),
  align = "h",
  nrow = 3
) 

p_turnover_enrichment_cow_v
# 
# cowplot::save_plot(filename = "fig_output/p_turnover_enrichment_cow_vertical.pdf",
#           plot = p_turnover_enrichment_cow_v,
#           base_height = 12,
#           base_width = 8
#           )
```


## Abundance versus turnover

```{r}
p_abundance_v_turnover <- turnover %>% 
  filter(inc_time_d != 0) %>% 
  ggplot(aes(
    x = compound_ug_per_g_soil,
    y = u_d,
    color = dF*10000
  )) +
  facet_wrap(vars(inc_time_d, soil), ncol = 3) +
  geom_point(alpha = 0.6) +
  scale_color_viridis_c() +
  theme_bw() +
  labs(x = "µg analyte per g soil",
       y = TeX("Turnover (d$^{-1}$)"),
       color = TeX("$ \\Delta ^2H$ (ppm)")
  ) +
  guides(color = guide_colorbar(barwidth = 0.5)) +
  theme(
    strip.background = element_blank(),
    
    panel.grid = element_blank(),
  )
p_abundance_v_turnover


cowplot::save_plot(filename = "fig_output/abundance_v_turnover.pdf",
                   plot = p_abundance_v_turnover,
                   base_height = 6,
                   base_width = 8)
```



## Literature Rates of Cell Turnover by Method


```{r lit rates}
literature_values_swatch <- c("#4ebad5", "#88e3cf", "#e388d7")
literature_values_swatch_2 <- c("#26AFE1", "#6269EB", "#E0187B")

p_lit_turnover_w_ours <- lit_turnover_w_ours %>%
  filter(method_type != "Microscopy") %>% 
  # order by mean turnover rate
  ggplot(
    aes(x = -n,
        y = u_d_mn,
        fill = method_type,
        label = round(gen_d, 1)
        )
    ) +
  geom_col() +
  geom_text(nudge_y = 0.05, size = 2) +
  coord_flip(ylim = c(0, 0.5)) +
  scale_fill_manual(values = literature_values_swatch_2) +
  labs(y = TeX("Turnover (d$^{-1}$)"),
       fill = "Method") +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 18),
        #legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        legend.position = c(0.85, 0.1),
        legend.text = element_text(size = 15),
        legend.title = element_blank(),
        plot.margin = margin(1,1,1.5,1.2, "in"))
p_lit_turnover_w_ours

cowplot::save_plot(filename = "fig_output/literature_values.pdf",
                   plot = p_lit_turnover_w_ours,
                   base_height = 8,
                   base_width = 10)
```


## BacDive FA profiles


```{r}
p_tax_FA <- bacdive_FA_wide %>% 
  select(-ID) %>% 
  pivot_longer(cols = -phylum, 
               names_to = "FA",
               values_to = "rel_abund") %>%
  ggplot(aes(x = FA, 
             y = rel_abund)) +
  geom_jitter(aes(color = phylum),
              size = 0.25,
              alpha = 0.3) +
  stat_pointinterval(point_interval = "median_qi",
                     alpha = 0.65) +
  facet_wrap(vars(phylum), nrow = 3) +
  scale_color_manual(values = c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#A65628", "#FF7F00", "#F781BF", "#999999")) +
  labs(y = "Relative Abundance (%)",
       x = "",
       color = "Phylum") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1),
        panel.grid = element_blank(),
        strip.background = element_blank(),
        legend.position = "NA",
        strip.text = element_text(size = 16)
        )

p_tax_FA

cowplot::save_plot(filename = "fig_output/p_tax_FA.pdf",
          plot = p_tax_FA,
          base_height = 11,
          base_width = 9
          )
```



## Compare extraction efficiency

```{r extr_eff}
FID_results_abundance_reported_long <- FID_results_abundance_no_stds %>% 
  select(
    sample_id, 
    compound, 
    deriv_efficiency, 
    extr_efficiency
  ) %>% 
  pivot_longer(
    !c(sample_id, compound),
    names_to = "stage", 
    values_to = "efficiency"
  ) %>% 
  mutate(
    stage = case_when(
      str_detect(stage, "deriv") ~ "Derivatization Efficiency",
      str_detect(stage, "extr") ~ "Extraction Efficiency"
    )
  )

FID_results_abundance_reported_long %>% 
  ggplot(aes(x = stage, y = efficiency)) +
  geom_boxplot(
    outlier.shape = NA,
    width = 0.3
    ) +
  coord_cartesian(ylim = c(0, 1.1)) +
  labs(x = "",
       y = "Efficiency") +
  theme_classic()
```



## Example chromatogram
```{r}
# plot an example chromatogram

sample_files[10] %>% # choosing arbitrary file to plot
  iso_plot_continuous_flow_data(
    # select data and aesthetics
    data = c(2), color = id1, panel = id1,
    # zoom in on time interval
    time_interval = c(750, 4000),
    # peak labels for all peaks > 2V
    peak_bounds = TRUE,
    peak_marker = FALSE,
    #peak_label_size = 3
    ) +
    scale_color_npg() +
    theme_classic() +
    theme(strip.background = element_blank())

```


## Turnover distributions


```{r turnover_across_soil}
p_turnover_distributions <- turnover %>% 
  filter(inc_time_d == 7) %>%
  mutate(terrain = case_when(
    terrain == "Gordon Gulch Conifer Forest" ~ "Conifer Forest",
    terrain == "Marshall Mesa Grassland" ~ "Grassland",
    terrain == "Niwot Ridge Tundra" ~ "Tunrda" )) %>% 
  mutate(terrain = forcats::fct_reorder(terrain, -u_d)) %>% 
  ggplot(
  aes(x = u_d, 
      y = terrain,
      color = terrain,
      fill = terrain)) +
  stat_slab(height = 0.5, 
            alpha = 0.7,
            color = "black") +
  stat_pointinterval(color = "black",
                     height = 0.2) +
  geom_point(
    color = "black",
    shape = 124,
    size = 5,
    alpha = 0.5,
    position = position_nudge(y = -.15)) +
  scale_x_log10(
    breaks = trans_breaks("log10", function(x) 10^x),
    labels = trans_format("log10", math_format(10^.x))
  ) +
  annotation_logticks(sides = "b") +
  scale_color_manual(values = terrain_color_swatch) +
  scale_fill_manual(values = terrain_fill_swatch) +
  theme_classic() +
  labs(y = "Soil Type",
       x = TeX("Turnover rate ($d^{-1}$)")) +
  theme(axis.text.y = element_text(hjust = 1),
        legend.position = "none")
p_turnover_distributions
```