---
title: "Paper Figures"
author: "Tristan Caro"
date: "`r Sys.Date()`"
output:
    html_document:
    code_folding: hide
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(tidyverse)    # CRAN v1.3.1 
library(forcats)      # CRAN v0.5.1 
library(isoreader)    # [::NA/NA] v1.3.0 # CRAN v1.3.0
library(isoprocessor) # [github::isoverse/isoprocessor] v0.6.7 
library(isotopia)     # [github::isoverse/isotopia] v0.5.8
library(readxl)       # CRAN v1.3.1
library(ggsci)        # CRAN v2.9 
'ggplot2' 
library(ggborderline) # [github::wurli/ggborderline] v0.1.0 
library(ggrepel)      # CRAN v0.9.1
'ggplot2' 
library(latex2exp)    # CRAN v0.5.0 
library(ggdist)       # CRAN v3.0.0 
library(ggsignif)     # CRAN v0.6.2
library(ggridges)     # CRAN v0.5.3
```


# Load Workspace Image

```{r}
load("cache/qSIP_calculations.RData")
```


# Plots

## Figure 1: Microbial turnover rate across soil types

```{r}

```

