---
title: "Analysis: NAME"
subtitle: "SUBTITLE"
author: "AUTHORS"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    css: stylesheet.css
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# load libraries
library(tidyverse) 
library(latex2exp)

# source functions
source(file.path("libs", "functions.R"))

# set global chunk options for figure output
figure_prefix <- "PREFIX-"
knitr::opts_chunk$set(
  dev=c("png", "pdf"), dev.args=list(pdf = list(encoding="WinAnsi", useDingbats=FALSE)),
  fig.keep="all", fig.path=file.path("figures", figure_prefix))
```

# Header A

```{r}
cars
```

# Header B

## Subheader C

```{r "cars", fig.width = 8, fig.height = 6}
cars %>% ggplot() + aes(speed, dist) + geom_point()
```

## Subheader D

```{r "latex", warning=FALSE}
iris %>% 
  mutate(
    latex_species = as_factor(Species) %>% 
      fct_recode(
        "$\\left(\\frac{\\textbf{setsoa}}{\\beta^2}\\right)$" = "setosa",
        "$\\int_{\\infinity}\\sqrt[2]_{\\textbf{versicolor}}$" = "versicolor")
  ) %>% 
  ggplot() + 
  aes(Sepal.Length, Sepal.Width, color = latex_species) + 
  geom_point() +
  scale_color_discrete(labels = latex_labeller) +
  facet_wrap(~latex_species, labeller = latex_labeller) +
  labs(x = TeX("my x axis $\\delta^{42}X\\,\\[\U2030\\]$")) + 
  theme_figure(text_size = 16)
```



