---
title: "Analysis: NAME"
subtitle: "SUBTITLE"
author: "AUTHORS"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    css: stylesheet.css
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: console
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# load libraries
library(tidyverse) 
library(latex2exp)
library(readxl)
library(isoreader)

# source functions
source(file.path("libs", "visualization.R"))
source(file.path("libs", "chromeleon"))

# set global chunk options for figure output
figure_prefix <- "PREFIX-"
knitr::opts_chunk$set(
  dev=c("png", "pdf"), dev.args=list(pdf = list(encoding="WinAnsi", useDingbats=FALSE)),
  fig.keep="all", fig.path=file.path("figures", figure_prefix))
```

# Load data

```{r}
root <- "data/gc_fid_data_2020/"
file_list = list.files(path = root)
all_data <-
  tibble(
    sample = file_list,
    file = file_list,
    data = map(file.path(root, file), read_chromeleon_export),
    injection_details = map(data, "injection_details"),
    integration_results = map(data, "integration_results")
  ) %>% select(-data)
```

## Show injection details

```{r}
all_data %>% select(-integration_results) %>% unnest(injection_details) %>% 
  knitr::kable()
```

# Analyze data

```{r}
results <- all_data %>% 
  select(-injection_details) %>% 
  unnest(integration_results) %>% 
  filter(nchar(`Peak Name`) > 0) %>% 
  # major compound groups
  mutate(
    group = `Peak Name` %>% str_remove("\\d+-OH") %>% parse_number() %>% abs() %>% {paste0("C", .)} %>% factor()
  ) 

results %>% 
  filter(!str_detect(`Peak Name`, fixed("?"))) %>% 
  ggplot() +
  aes(`Peak Name`, `Relative Area`) +
  geom_bar(stat = "identity") +
  theme_figure(axis_x_rotate = 90) +
  scale_y_continuous(expand = c(0,0)) +
  facet_wrap(~sample)
```

```{r}
results %>% 
  ggplot() +
  aes(`Retention Time`, `Relative Height`, fill = `Peak Name`) +
  geom_bar(stat = "identity")
```


```{r}
results %>% 
  ggplot() +
  aes(`Retention Time`, `Relative Height`, fill = group, label = `Peak Name`) +
  geom_bar(stat = "identity") +
  facet_grid(sample ~ .) +
  theme_figure(legend = TRUE) +
  scale_y_continuous(expand = c(0, 0))
```

```{r}
library(plotly)
ggplotly(ggplot2::last_plot(), dynamicTicks = TRUE)
```

# export data

```{r}
results %>% 
  filter(sample == "a") %>% 
  mutate(rt = `Retention Time` * 60) %>% 
  select(group, `Peak Name`, rt, rel_height = `Relative Height`) %>% 
  mutate(rt = round(rt, 1), rel_height = round(rel_height, 2)) %>%
  filter(rel_height > 1) %>% 
  openxlsx::write.xlsx(file.path("tables", "tsq_single_sample_peak_table.xlsx"))
```

